[package]
name = "web-tbd-front"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-cors = "0.7.0"
actix-proxy = "0.2.0"
actix-web = "4.5.1"
